name       : plasma-desktop
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/plasma-desktop-5.9.5.tar.xz : e1f437ac86e91e7f18a1e36dc93c3e8e57a0e183f343765f3772a902f0c135b9
license    :
    - GFDL-2.0
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(gl)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libevdev)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libKF5Attica)
    - pkgconfig(libpulse)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - breeze-devel
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kinit-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpeople-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwallet-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
    - xorg-driver-input-evdev-devel
    - xorg-driver-input-synaptics-devel
rundeps    :
    - xprop
    - xset
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
