name       : plasma-desktop
version    : 5.21.3
release    : 84
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/plasma-desktop-5.21.3.tar.xz : de4f62f6e4612fd796387825cd755edde4784c0386c0d0552deb3b3c44993e2f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
optimize   : lto
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-evdev)
    - pkgconfig(xorg-libinput)
    - pkgconfig(xorg-server)
    - pkgconfig(xorg-synaptics)
    - baloo-devel
    - breeze-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kglobalaccel-devel
    - kirigami2-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwallet-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - plasma-workspace-devel
    - qqc2-desktop-style-devel
rundeps    :
    - accountsservice
    - frameworkintegration
    - kded
    - kio-extras
    - qt5-graphicaleffects
    - qt5-quickcontrols2
patterns   :
    - /usr/lib64/libkdeinit5*.so
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
