name       : plasma-desktop
version    : 5.10.5
release    : 7
source     :
    - https://download.kde.org/stable/plasma/5.10.5/plasma-desktop-5.10.5.tar.xz : 15bfd43b9589654f1c8c56601fc392a1a16f07b2979ae1d92d4f9570c514beeb
license    :
    - GFDL-2.0
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(gl)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libevdev)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libKF5Attica)
    - pkgconfig(libpulse)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-evdev)
    - pkgconfig(xorg-server)
    - pkgconfig(xorg-synaptics)
    - breeze-devel
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kinit-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpeople-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwallet-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
rundeps    :
    - frameworkintegration
    - kded
    - kio-extras
    - qt5-graphicaleffects
    - xprop
    - xset
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
