name       : plasma-desktop
version    : 5.16.5
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/plasma-desktop-5.16.5.tar.xz : 49dc4c9eff5742eb52fc0d12c139c194eda837945389cd09f498a0c4c352a20f
license    :
    - GFDL-2.0
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libKF5Attica)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-evdev)
    - pkgconfig(xorg-libinput)
    - pkgconfig(xorg-server)
    - pkgconfig(xorg-synaptics)
    - breeze-devel
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kinit-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kpeople-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwallet-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
rundeps    :
    - frameworkintegration
    - kded
    - kio-extras
    - qt5-graphicaleffects
    - qt5-quickcontrols2
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-tweaks-to-the-default-config.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
