name       : plasma-desktop
version    : 5.18.5
release    : 66
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/plasma-desktop-5.18.5.tar.xz : aeb106018fd90da79c8a3c444d880282846a842029b1223e7830db2d4b42df9f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0
    - GPL-2.0
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE's next generation desktop
description: |
    KDE's next generation desktop.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libKF5Attica)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xcb-atom)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-image)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-evdev)
    - pkgconfig(xorg-libinput)
    - pkgconfig(xorg-server)
    - pkgconfig(xorg-synaptics)
    - breeze-devel
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kinit-devel
    - kirigami2-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - krunner-devel
    - kscreenlocker-devel
    - kwallet-devel
    - kwin-devel
    - libboost-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
    - qqc2-desktop-style-devel
rundeps    :
    - frameworkintegration
    - kded
    - kio-extras
    - qt5-graphicaleffects
    - qt5-quickcontrols2
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
